name: HeartModelling
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - blas=1.0=mkl
  - bottleneck=1.3.2=py310h9128911_1
  - bzip2=1.0.8=h8ffe710_4
  - ca-certificates=2022.10.11=haa95532_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cftime=1.5.1.1=py310h2873277_1
  - colorama=0.4.4=pyh9f0ad1d_0
  - curl=7.80.0=h789b8ee_1
  - h5py=3.6.0=nompi_py310h00cbb18_100
  - hdf4=4.2.15=h0e5069d_3
  - hdf5=1.12.1=nompi_h57737ce_103
  - icc_rt=2019.0.0=h0cc432a_1
  - importlib-metadata=4.8.2=py310h5588dad_0
  - importlib_metadata=4.8.2=hd8ed1ab_0
  - intel-openmp=2021.4.0=h57928b3_3556
  - jpeg=9d=h8ffe710_0
  - krb5=1.19.2=h6da9e4a_3
  - libblas=3.9.0=12_win64_mkl
  - libcblas=3.9.0=12_win64_mkl
  - libcurl=7.80.0=h789b8ee_1
  - libffi=3.4.2=h8ffe710_5
  - libiconv=1.16=h2bbff1b_2
  - liblapack=3.9.0=12_win64_mkl
  - libnetcdf=4.8.1=nompi_h1cc8e9d_101
  - libssh2=1.10.0=h9a1e1f7_2
  - libxml2=2.9.12=h0ad7f3c_0
  - libxslt=1.1.34=he774522_0
  - libzip=1.8.0=h519de47_1
  - libzlib=1.2.11=h8ffe710_1013
  - llvmlite=0.39.1=py310h23ce68f_0
  - lxml=4.8.0=py310h1985fb9_0
  - meshio=5.1.1=pyhd8ed1ab_0
  - mkl=2021.4.0=h0e2418a_729
  - mkl-service=2.4.0=py310h2bbff1b_0
  - mkl_fft=1.3.1=py310ha0764ea_0
  - mkl_random=1.2.2=py310h4ed8f06_0
  - netcdf4=1.5.8=nompi_py310h5489b47_101
  - nibabel=3.2.2=pyhd8ed1ab_0
  - npx=0.0.24=pyhd8ed1ab_0
  - numba=0.56.3=py310h4ed8f06_0
  - numexpr=2.8.1=py310hb57aa6b_1
  - numpy=1.21.5=py310h4c31df0_0
  - numpy-base=1.21.5=py310hedd7904_0
  - openssl=3.0.2=h8ffe710_0
  - packaging=20.4=py_0
  - pandas=1.4.1=py310hd77b12b_0
  - pip=21.3.1=pyhd8ed1ab_0
  - pydicom=2.2.2=pyh6c4a22f_0
  - pyparsing=2.4.7=py_0
  - python=3.10.0=hcf16a7b_3_cpython
  - python-dateutil=2.8.1=py_0
  - python_abi=3.10=2_cp310
  - pytz=2020.1=py_0
  - scipy=1.7.3=py310h6d2d95c_0
  - setuptools=59.4.0=py310h5588dad_0
  - six=1.15.0=py_0
  - sqlite=3.37.0=h8ffe710_0
  - tbb=2021.4.0=h2d74725_1
  - tk=8.6.11=h8ffe710_1
  - tqdm=4.63.0=pyhd8ed1ab_0
  - tzdata=2021e=he74cb21_0
  - ucrt=10.0.20348.0=h57928b3_0
  - vc=14.2=hb210afc_5
  - vs2015_runtime=14.29.30037=h902a5da_5
  - wheel=0.37.0=pyhd8ed1ab_1
  - xz=5.2.5=h62dcd97_1
  - zipp=3.6.0=pyhd8ed1ab_0
  - zlib=1.2.11=h8ffe710_1013
  - pip:
    - cycler==0.11.0
    - fonttools==4.31.2
    - kiwisolver==1.4.2
    - mat73==0.59
    - matplotlib==3.5.1
    - pillow==9.0.1
    # - pygeodesic==0.1.7
    - pynrrd==0.4.3
    - seaborn==0.11.2
prefix: C:\Users\usuario\anaconda3\envs\HeartModelling
